config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: "admin#show_post", as: 'admin_post'
  end

  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/u/:id', to: 'users#profile', as: 'user'

  post "u/make_admin" => "users#make_admin"
  post "u/make_user" => "users#make_user"
  delete "u/:id" => "users#destroy"
  
  resources :projects do
    resources :tasks
    resources :orderables, shallow: true
  end

  resources :categories do
    resources :products, shallow: true 
  end

  resources :posts do 
    resources :comments
  end
  
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :image
  has_many :products, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validate :validate_file_type

  def validate_file_type
    return unless image.attached?
    unless image.content_type.in?(%w[image/jpeg image jpg image/png])
      errors.add(:image, "Must be a JPEG, JPG or PNG")
    end
  end


  def image_resized2
    image.variant(resize_to_limit: [300,260]).processed
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :project

  delegate :name, to: :product, prefix: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :body, presence: true, length: { minimum: 10, maximum: 1500 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_rich_text :body
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one_attached :image
  has_many :orderables
  has_many :projects, through: :orderables
  has_one :stock_item, dependent: :destroy
  accepts_nested_attributes_for :stock_item, update_only: true
  validates :model, presence: true
  validates :name, presence: true
  validates :manufacturer, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :price, presence: true
  validate :validate_file_type
  
  def validate_file_type
    return unless image.attached?
    unless image.content_type.in?(%w[image/jpeg image jpg image/png])
      errors.add(:image, "Must be a JPEG, JPG or PNG")
    end
  end


  def create_stock_item
    self.stock_item ||= StockItem.new[product: self]
  end

  def image_resized
    image.variant(resize_to_limit: [300,260]).processed
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :orderables
  has_many :products, through: :orderables
  has_rich_text :description
  has_one_attached :agreement, dependent: :destroy
  geocoded_by :address do |object, results|
    if results.present?
     object.latitude = results.first.latitude
     object.longitude = results.first.longitude
    else
     object.latitude = nil
     object.longitude = nil
    end
  end
  after_validation :geocode
  validates :name, presence: true
  validates :description, presence: true
  validates :deadline, presence: true
  validates :agreement, presence: true
  validate :validate_file_type
  before_validation :geocode, if: :address_changed?
  validates :address, presence: true
  validate :found_address_presence
  validates :status, inclusion: { in: [ 'to do', 'in progress', 'completed'] }
  STATUS_OPTIONS = [
    ['To Do', 'to do'],
    ['In Progress', 'in progress'],
    ['Completed', 'completed'],
  ]
  def badge_color
    case status
    when 'to do'
      'secondary'
    when 'in progress'
      'info'
    when 'completed'
      'success'
    end
  end

  def validate_file_type
    return unless agreement.attached?
    unless agreement.content_type.in?(%w[application/pdf])
      errors.add(:agreement, "Must be a PDF")
    end
  end

  def self.total_project_cost(project)
    total_price = 0.00
    project.orderables.each do |orderable|
      total_price = total_price + orderable.quantity * orderable.product.price.to_f
    end
    total_price
  end

  def found_address_presence
    if latitude.blank? || longitude.blank?
      errors.add(:address, "We couldn't find the address")
    end
  end

end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :product
  validates :quantity_available, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_rich_text :description
  validates :name, presence: true
  validates :description, presence: true
  validates :status, inclusion: { in: [ 'to do', 'in progress', 'completed'] }
  STATUS_OPTIONS = [
    ['To Do', 'to do'],
    ['In Progress', 'in progress'],
    ['Completed', 'completed'],
  ]
  def badge_color
    case status
    when 'to do'
      'secondary'
    when 'in progress'
      'info'
    when 'completed'
      'success'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :full_name #for full name validation
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_one_attached :avatar
  validate :validate_file_type

  def validate_file_type
    return unless avatar.attached?
    unless avatar.content_type.in?(%w[image/jpeg image jpg image/png])
      errors.add(:avatars, "Must be a JPEG, JPG or PNG")
    end
  end


  # def email_required? for disabling required errors from the devise library, search for the errors in yml file?
  #   true
  # end 

  enum role: [:user, :admin]
  after_initialize  :set_default_role, if: :new_record?

  private
    def set_default_role
      self.role ||= :user
    end
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_admin_nav.html.erb
<div class="container text-center">
  <div>
    <%= link_to 'Admin', admin_path, class: "link-dark" %> <%= " > #{params[:action]}" unless params[:action].eql?('index')%>
  </div>
  <div class="btn-group mr2" role="group">
    <%= render "admin/link", resource: Post, class: "link-light" %>
    <%#= render "admin/link", resource: Comment %>
    <%= render "admin/link", resource: User %>
  </div>

</div>

app/views/admin/_link.html.erb
<%= link_to resource.name, url_for([:admin, resource]), class: 'link-dark' %>

app/views/admin/comments.html.erb
<div class = "container">
  <h1 class="text-center"> Administrator </h1>
  <%= render 'admin/admin_nav'%>
</div>
<h1>Admin#comments</h1>
<p>Find me in app/views/admin/comments.html.erb</p>

app/views/admin/index.html.erb
<div class = "container">
  <h1 class="text-center"> Administrator </h1>
  <%= render 'admin/admin_nav'%>
</div>

app/views/admin/posts.html.erb
<div class = "container">
  <h1 class="text-center"> Administrator </h1>
  <%= render 'admin/admin_nav'%>
</div>
<table class="table table dark table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Post</th>
      <th scope="col">Author</th>
      <th scope="col">Comments</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th scope="row"><%= post.id %></th>
        <td><%= link_to post.title.truncate(15), admin_post_path(post), class: "link-dark" %></td>
        <td><%= post.user.full_name %></td>
        <td><%= pluralize(post.comments.size, "Comment") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/show_post.html.erb
<div class="container">
  <h1 class="text-center">Administrator</h1>
  <%= render 'admin/admin_nav' %>
  <div class="text-center mt-5">
    <div class="btn-group">
      <%= link_to "Edit", edit_post_path(@post), class: "btn btn-warning" %>
      <%= button_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div> 
  </div>
  <div class="row mt-1">
    <p>
      <strong> Title: </strong> <%= @post.title %>
    </p>
  </div>
  <div class="row mt-1">
    <p>
      <strong> Author: </strong> <%= "#{@post.user.full_name} | #{@post.user.email}" %>
    </p>
  </div>
  <div class="row mt-1">
    <p>
      <strong> Body: </strong> <%= @post.body %>
    </p>
  </div>
  <div class="row mt-1">
    <p>
      <strong><%= pluralize(@post.comments.count, "Comment") %></strong>
    </p>
    <% @post.comments.each do |comment| %>
      <div class="row mt-1">
        <%= comment.user.full_name %>
        <%= comment.body %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users.html.erb
<div class = "container">
  <h1 class="text-center"> Administrator </h1>
  <%= render 'admin/admin_nav'%>
</div>
<table class="table table dark table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">User name</th>
      <th scope="col">E-mail</th>
      <th scope="col">Posts</th>
      <th scope="col">Comments</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= link_to user.full_name, user_path(user), class: "link-dark" %></td>
        <td><%= user.email %></td>
        <td><%= pluralize(user.posts.size, "Posts") %></td>
        <td><%= pluralize(user.comments.size, "Comment") %></td>
      </tr>
    <% end %>
  </tbody>
</table>