config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: "admin#show_post", as: 'admin_post'
  end

  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/u/:id', to: 'users#profile', as: 'user'

  post "u/make_admin" => "users#make_admin"
  post "u/make_user" => "users#make_user"
  delete "u/:id" => "users#destroy"
  
  resources :projects do
    resources :tasks
    resources :orderables, shallow: true
  end

  resources :categories do
    resources :products, shallow: true 
  end

  resources :posts do 
    resources :comments
  end
  
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :orderables
  has_many :products, through: :orderables
  has_rich_text :description
  has_one_attached :agreement, dependent: :destroy
  geocoded_by :address do |object, results|
    if results.present?
     object.latitude = results.first.latitude
     object.longitude = results.first.longitude
    else
     object.latitude = nil
     object.longitude = nil
    end
  end
  after_validation :geocode
  validates :name, presence: true
  validates :description, presence: true
  validates :deadline, presence: true
  validates :agreement, presence: true
  validate :validate_file_type
  before_validation :geocode, if: :address_changed?
  validates :address, presence: true
  validate :found_address_presence
  validates :status, inclusion: { in: [ 'to do', 'in progress', 'completed'] }
  STATUS_OPTIONS = [
    ['To Do', 'to do'],
    ['In Progress', 'in progress'],
    ['Completed', 'completed'],
  ]
  def badge_color
    case status
    when 'to do'
      'secondary'
    when 'in progress'
      'info'
    when 'completed'
      'success'
    end
  end

  def validate_file_type
    return unless agreement.attached?
    unless agreement.content_type.in?(%w[application/pdf])
      errors.add(:agreement, "Must be a PDF")
    end
  end

  def self.total_project_cost(project)
    total_price = 0.00
    project.orderables.each do |orderable|
      total_price = total_price + orderable.quantity * orderable.product.price.to_f
    end
    total_price
  end

  def found_address_presence
    if latitude.blank? || longitude.blank?
      errors.add(:address, "We couldn't find the address")
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all.order(created_at: :asc)
  end

  # GET /projects/1 or /projects/1.json
  def show
    @tasks = @project.tasks
    
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)


    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id, :status, :address, :deadline, :agreement)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :deadline, style: "display: block" %>
    <%= form.date_field :deadline, value: form.object.try(:strftime,"%m/%d/%Y") %>
  </div>

  <div>
    <%= form.label :agreement, style: "display: block" %>
    <%= form.file_field :agreement %>
  </div>

  <div>
    <%= form.label :status %>
    <%= form.select :status, Project::STATUS_OPTIONS %>
  </div>

  <div>
    <%= form.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/projects/_orderable.html.erb
<div class="container">
  <div>
  <h6> Product name: <%= orderable.product.name %> </h6>
  <h6> Product quantity: <%= orderable.quantity %> </h6>
  <h6> Product total cost: <%= number_to_currency((orderable.quantity * orderable.product.price), unit: "€", separator: ",") %> </h6>
  </div>
  <div class="row">
    <div class="col-2">
      <div class="btn btn-group">
        <%= link_to "Edit", edit_orderable_path(orderable), class: "btn btn-light btn btn-outline-dark" %>
        <%= button_to "Delete", orderable_path(orderable), method: :delete, class: "btn btn-dark" %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <div class="container">
    <div>
    <span class="badge rounded-pill bg-<%= project.badge_color %>"><%= project.status %></span>
    </div>
    <h2><%= project.name %></h2>
    <div id="address" data-address="<%= project.address%>">
      <h5>Project address: <%= project.address %></h5>
    </div>
    <div id="map" data-lat="<%= project.latitude %>" data-lon="<%= project.longitude %>" >
    </div>
    <div>
      <h6>Project deadline: <%= project.deadline.strftime("%d/%m/%Y") %></h6>
    </div>
    <p> Project manager: <%= project.user.full_name %></p>
    <div>
      <p><%= project.description %></p>
    </div>
</div>

app/views/projects/edit.html.erb
<div class="ms-4">
  <h1>Editing project</h1>

  <%= render "form", project: @project %>

  <br>

  <div>
    <%= link_to "Show this project", @project, class: "btn btn-light btn btn-outline-dark" %>
    <%= link_to "Back to projects", projects_path, class: "btn btn-light btn btn-outline-dark" %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="container card mt-5 mb-5">
    <br />
    <h2 class="card-title d-flex justify-content-between mt-3 mb-3"><span>Projects</span>
    <%= link_to "New project", new_project_path, class: "btn btn-dark" if current_user.admin? %>
    </h2>
    <br />

    <div id="projects" class="container mb-5">
      <% @projects.each do |project| %>
        <div class="card mb-3">
          <%= render project %>
            <div class="btn btn-group">
            <p>
              <%= link_to "Show this project", project, class: "btn btn-dark ms-3" %>
            </p>
            <p>
              <%= link_to "Edit this project", edit_project_path(project), class: "btn btn-dark ms-3" if current_user.admin? %>
            </p>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="ms-5">
  <h1>New project</h1>

  <%= render "form", project: @project %>

  <br>

  <div>
    <%= link_to "Back to projects", projects_path, class: "btn btn-dark" %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container mb-2">
  <%= render @project %>
  <div class="btn btn-group">
    <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-light btn btn-outline-dark mb-2 ms-3" if current_user == @project.user %> 
    <%= link_to "Back to projects", projects_path, class: "btn btn-light btn btn-outline-dark ms-2 mb-2" %>
    
    <%= button_to "Delete this project", @project, method: :delete, class: "btn btn-dark ms-2" if current_user == @project.user  %>
  </div>
  <div>
    <h6> Total Project cost: <%= number_to_currency((Project::total_project_cost(@project)), separator: ',', unit: '€') %> </h6>
    <%= link_to "Download Agreement", url_for(@project.agreement), class: "link link-dark" if @project.agreement.attached? && current_user == @project.user%>
    <div class="leaflet-container" style="min-height: 400px; max-width: 600px;" data-controller="map" data-map-target="placeholder">
  </div>

  <hr/>
  <div class="mb-5"><h4> Adding Products </h4>
  <%= form_with(model: Orderable.new, url: project_orderables_path(@project)) do |f| %>
    <%= f.hidden_field :project_id, value: @project.id %>
    <%= f.select :product_id, Product.where.not(id: Product.includes(:orderables).where(orderables: { project_id: [@project.id] }).ids).collect{ |p| [p.name, p.id] }, class: "form-select form-select-sm" %>
    <%= f.number_field :quantity, value: 1, min: 1 %>
    <%= f.submit 'Add Product', class: "btn btn-dark" %>
  <% end %>
  </div>
  <hr/>
  <h4> Project Products: </h4>
  <%= render partial: 'projects/orderable', collection: @project.orderables, locals: { project: @project } %>

</div>

<hr/>

<div class="container">
  <h4> Additional Tasks </h4>
  <div id="options" data-controller="visibility">
    <button class="btn btn-dark" data-action="visibility#toggleTargets">New Task</button>
    <div data-visibility-target="hideable" hidden><%= render 'tasks/form', project: @project, task: Task.new(project: @project), label_for_submit: "Create" %></div>
  </div>
  <% @tasks.each do |task| %>
    <%= render 'tasks/task', project: @project, task: task %>
  <% end %>
</div>